[config]
default_to_workspace = false

[tasks.gh-gdb-build-prod]
command = "cargo"
args = ["build", "--release"]

[tasks.gh-gdb-create-dist-folder]
command = "mkdir"
args = [
    "-p",
    "${HOME}/.local/share/gh/extensions/gh-gdb",
]

[tasks.gh-gdb-install]
command = "cp"
args = [
    "./target/release/gh-gdb",
    "${HOME}/.local/share/gh/extensions/gh-gdb/gh-gdb",
]
dependencies = ["gh-gdb-build-prod", "gh-gdb-create-dist-folder"]
