[config]
default_to_workspace = false

[tasks.gh-tun-build-prod]
command = "cargo"
args = ["build", "--release"]

[tasks.gh-tun-create-dist-folder]
command = "mkdir"
args = [
    "-p",
    "${HOME}/.local/share/gh/extensions/gh-oocd",
]

[tasks.gh-oocd-install]
command = "cp"
args = [
    "./target/release/gh-extension",
    "${HOME}/.local/share/gh/extensions/gh-oocd/gh-oocd",
]
dependencies = ["gh-oocd-build-prod", "gh-oocd-create-dist-folder"]
